### ISSUE TITLE
cannot load the Toolchain UI sometimes

### ISSUE THREAD

**Issue by dshuffma-ibm** [open-toolchain/sdk#13]
fairly often I cannot load the Toolchain UI.  I see the screen shot below:

https://console.stage1.bluemix.net/devops/toolchains?env_id=ibm:ys1:us-south

![image](https://user-images.githubusercontent.com/16085295/37465673-2c1d3722-2832-11e8-9f60-fbbe349b75ca.png)

I'm seeing this on the staging url. It seems to fix itself if I close the browser and login again. Also the rest of the bluemix UI is fine. I can get to the catalog and my apps dashboard.

**Comment by hmagph** [comment]
We delivered recently a set of changes to eradicate many of the underlying calls to CF API which were causing trouble in multiple ways, using newest IBM Cloud auth api (IAM).
This occurred in 2 waves, first in July, and second early September.
This problem should thus be gone.
